import Head from "next/head";
import estilos from "@/styles/Home.module.css";
import Topo from "@/componentes/Topo";
import SecaoCapa from "@/componentes/SecaoCapa";
import SecaoSobre from "@/componentes/SecaoSobre";
import SecaoProdutos from "@/componentes/SecaoProdutos";
import SecaoContatos from "@/componentes/SecaoContatos";
import Rodape from "@/componentes/Rodape";



export default function Home() {
  return (
    <>
      <Head>
        <title>Óticas Vida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={estilos.home}>
        <Topo />
        <SecaoCapa />
        <SecaoProdutos />
        <SecaoSobre />
        <SecaoContatos />
        <Rodape />
      </main>
     
    </>
  );
}
